# Generated by Django 2.1.15 on 2020-06-19 21:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_model'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Model',
            new_name='Ingredient',
        ),
    ]
